version: ~> 1.0

import:
  - source: node_modules/@woocommerce/e2e-env/.travis.yml
    mode: deep_merge_prepend # Merge the package config first.

jobs:
    fast_finish: true
    include:
        - stage: build tests
          name: PHP 7.1/unit-tests/Latest WP
          php: 7.1
          env:
              - WP_VERSION=latest
              - WOOCOMMERCE_BLOCKS_PHASE=experimental
          script:
              - phpunit
        - name: PHP 5.6/unit-tests/Latest WP
          php: 5.6
          env:
              - WP_VERSION=latest
              - WOOCOMMERCE_BLOCKS_PHASE=experimental
          script:
              - phpunit
        - name: PHP Linting Check
          php: 7.1
          env:
              - WP_TRAVISCI=phpcs
              - WOOCOMMERCE_BLOCKS_PHASE=experimental
          script:
              - npm run lint:php
        - name: Javascript Tests
          script:
              - npm install
              - npm run test
          env:
            - WOOCOMMERCE_BLOCKS_PHASE=experimental
        - name: Javascript/CSS Lint and Bundle Size Check
          script:
              - npm install
              - npm run build:ci
          env:
            - WOOCOMMERCE_BLOCKS_PHASE=experimental
